# name: Manually triggered workflow
# on:
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Person to greet'
#         required: true
#         default: 'Mona the Octocat'
#       home:
#         description: 'location'
#         required: false
#         default: 'The Octoverse'

# jobs:
#   say_hello:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "Hello ${{ github.event.inputs.name }}!"
#           echo "- in ${{ github.event.inputs.home }}!"



name: Reseed Database
on: 
  push:
    branches: [ main, NewGithubAction]

jobs:

  database-reseed: 
    runs-on: ubuntu-latest

    # needs: build

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Empty and re-seed database
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "e-chronicler"
      run: | 
        ecto.drop 
        ecto.create 
        ecto.migrate 
        run priv/repo/seeds.exs