name: Reseed Database

on: workflow_dispatch

jobs:

  database-reseed: 
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Empty and re-seed database
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "e-chronicler"
      run: | 
      ecto.drop 
      ecto.create 
      ecto.migrate 
      run priv/repo/seeds.exs